using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flowing
{
    public class IConstants
    {
        public int X = 0;
        public int Y = 1;
        public int Z = 2;
        public String JAVA2D = "processing.core.PGraphicsJava2D";
        public String P2D = "processing.opengl.PGraphics2D";
        public String P3D = "processing.opengl.PGraphics3D";
        public String OPENGL = "processing.opengl.PGraphics3D";
        public String PDF = "processing.pdf.PGraphicsPDF";
        public String DXF = "processing.dxf.RawDXF";
        public int OTHER = 0;
        public int WINDOWS = 1;
        public int MACOSX = 2;
        public int LINUX = 3;
        public String[] platformNames = new String[] { "other", "windows", "macosx", "linux" };
        public float EPSILON = 1.0E-4F;
        public float MAX_float = 3.4028235E38F;
        public float MIN_float = -3.4028235E38F;
        public int MAX_int = 2147483647;
        public int MIN_int = -2147483648;
        public int VERTEX = 0;
        public int BEZIER_VERTEX = 1;
        public int QUADRATIC_VERTEX = 2;
        public int CURVE_VERTEX = 3;
        public int BREAK = 4;
        /** @deprecated */
        //@Deprecated
        public int QUAD_BEZIER_VERTEX = 2;
        public float PI = 3.1415927F;
        public float HALF_PI = 1.5707964F;
        public float THIRD_PI = 1.0471976F;
        public float QUARTER_PI = 0.7853982F;
        public float TWO_PI = 6.2831855F;
        public float TAU = 6.2831855F;
        public float DEG_TO_RAD = 0.017453292F;
        public float RAD_TO_DEG = 57.295776F;
        public String WHITESPACE = " \t\n\r\f ";
        public int RGB = 1;
        public int ARGB = 2;
        public int HSB = 3;
        public int ALPHA = 4;
        public int TIFF = 0;
        public int TARGA = 1;
        public int JPEG = 2;
        public int GIF = 3;
        public int BLUR = 11;
        public int GRAY = 12;
        public int INVERT = 13;
        public int OPAQUE = 14;
        public int POSTERIZE = 15;
        public int THRESHOLD = 16;
        public int ERODE = 17;
        public int DILATE = 18;
        public int REPLACE = 0;
        public int BLEND = 1;
        public int ADD = 2;
        public int SUBTRACT = 4;
        public int LIGHTEST = 8;
        public int DARKEST = 16;
        public int DIFFERENCE = 32;
        public int EXCLUSION = 64;
        public int MULTIPLY = 128;
        public int SCREEN = 256;
        public int OVERLAY = 512;
        public int HARD_LIGHT = 1024;
        public int SOFT_LIGHT = 2048;
        public int DODGE = 4096;
        public int BURN = 8192;
        public int CHATTER = 0;
        public int COMPLAint = 1;
        public int PROBLEM = 2;
        public int PROJECTION = 0;
        public int MODELVIEW = 1;
        public int CUSTOM = 0;
        public int ORTHOGRAPHIC = 2;
        public int PERSPECTIVE = 3;
        public int GROUP = 0;
        public int POint = 2;
        public int POintS = 3;
        public int LINE = 4;
        public int LINES = 5;
        public int LINE_STRIP = 50;
        public int LINE_LOOP = 51;
        public int TRIANGLE = 8;
        public int TRIANGLES = 9;
        public int TRIANGLE_STRIP = 10;
        public int TRIANGLE_FAN = 11;
        public int QUAD = 16;
        public int QUADS = 17;
        public int QUAD_STRIP = 18;
        public int POLYGON = 20;
        public int PATH = 21;
        public int RECT = 30;
        public int ELLIPSE = 31;
        public int ARC = 32;
        public int SPHERE = 40;
        public int BOX = 41;
        public int OPEN = 1;
        public int CLOSE = 2;
        public int CORNER = 0;
        public int CORNERS = 1;
        public int RADIUS = 2;
        public int CENTER = 3;
        public int DIAMETER = 3;
        public int CHORD = 2;
        public int PIE = 3;
        public int BASELINE = 0;
        public int TOP = 101;
        public int BOTTOM = 102;
        public int NORMAL = 1;
        public int IMAGE = 2;
        public int CLAMP = 0;
        public int REPEAT = 1;
        public int MODEL = 4;
        public int SHAPE = 5;
        public int SQUARE = 1;
        public int ROUND = 2;
        public int PROJECT = 4;
        public int MITER = 8;
        public int BEVEL = 32;
        public int AMBIENT = 0;
        public int DIRECTIONAL = 1;
        public int SPOT = 3;
        char BACKSPACE = '\b';
        char TAB = '\t';
        char ENTER = '\n';
        char RETURN = '\r';
        char ESC = '\u001b';
        char DELETE = '\u007f';
        public int CODED = 65535;
        public int UP = 38;
        public int DOWN = 40;
        public int LEFT = 37;
        public int RIGHT = 39;
        public int ALT = 18;
        public int CONTROL = 17;
        public int SHIFT = 16;
        public int PORTRAIT = 1;
        public int LANDSCAPE = 2;
        public int ARROW = 0;
        public int CROSS = 1;
        public int HAND = 12;
        public int MOVE = 13;
        public int TEXT = 2;
        public int WAIT = 3;
        /** @deprecated */
        //@Deprecated
    public int ENABLE_NATIVE_FONTS = 1;
        /** @deprecated */
        //@Deprecated
    public int DISABLE_NATIVE_FONTS = -1;
        public int DISABLE_DEPTH_TEST = 2;
        public int ENABLE_DEPTH_TEST = -2;
        public int ENABLE_DEPTH_SORT = 3;
        public int DISABLE_DEPTH_SORT = -3;
        public int DISABLE_OPENGL_ERRORS = 4;
        public int ENABLE_OPENGL_ERRORS = -4;
        public int DISABLE_DEPTH_MASK = 5;
        public int ENABLE_DEPTH_MASK = -5;
        public int DISABLE_OPTIMIZED_STROKE = 6;
        public int ENABLE_OPTIMIZED_STROKE = -6;
        public int ENABLE_STROKE_PERSPECTIVE = 7;
        public int DISABLE_STROKE_PERSPECTIVE = -7;
        public int DISABLE_TEXTURE_MIPMAPS = 8;
        public int ENABLE_TEXTURE_MIPMAPS = -8;
        public int ENABLE_STROKE_PURE = 9;
        public int DISABLE_STROKE_PURE = -9;
        public int ENABLE_RETINA_PIXELS = 10;
        public int DISABLE_RETINA_PIXELS = -10;
        public int Hint_COUNT = 11;
        public String ERROR_BACKGROUND_IMAGE_SIZE = "background image must be the same size as your application";
        public String ERROR_BACKGROUND_IMAGE_FORMAT = "background images should be RGB or ARGB";
        public String ERROR_TEXTFONT_NULL_PFONT = "A null PFont was passed to textFont()";
        public String ERROR_PUSHMATRIX_OVERFLOW = "Too many calls to pushMatrix().";
        public String ERROR_PUSHMATRIX_UNDERFLOW = "Too many calls to popMatrix(), and not enough to pushMatrix().";
    }
}
